### ISSUE TITLE
k_neighbors missing?

### ISSUE THREAD

**Issue by Leo-T-Zang** [A4Bio/FoldToken_open#1]
Hi @gaozhangyang,

I think in your `config.yaml` for foldtoken, it might miss `k_neighbors` as the follwoing error occurs

```
Traceback (most recent call last):
  File "/root/miniconda3/envs/flash/lib/python3.9/site-packages/lightning_fabric/utilities/data.py", line 487, in __getattr__
    return self[key]
KeyError: 'k_neighbors'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/FoldToken_open/foldtoken/reconstruct.py", line 38, in <module>
    model = load_model(args)
  File "/foldtoken/FoldToken_open/foldtoken/reconstruct.py", line 15, in load_model
    model = MInterface(**config)
  File "/foldtoken/FoldToken_open/foldtoken/model_interface.py", line 28, in __init__
    super().__init__()
  File "/foldtoken/FoldToken_open/foldtoken/src/interface/model_interface.py", line 13, in __init__
    self.load_model()
  File "/foldtoken/FoldToken_open/foldtoken/model_interface.py", line 60, in load_model
    self.model = PiFold_Model(self.hparams)
  File "/foldtoken/FoldToken_open/foldtoken/src/models/FoldToken4.py", line 28, in __init__
    self.top_k = args.k_neighbors
  File "/root/miniconda3/envs/flash/lib/python3.9/site-packages/lightning_fabric/utilities/data.py", line 489, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{key}'") from e
AttributeError: 'AttributeDict' object has no attribute 'k_neighbors'
```

**Comment by dandingsky** [comment]
Hi, did you find out how to solve this issue?
